# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Executable

on:
  push:
    tags: 
      - 'v*.*.*'

jobs:
    
  build:
    runs-on: ubuntu-latest
          
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
      
    - name: Build MacOS
      shell: bash
      run: |
        tag=$(git describe --tags --abbrev=0)
        
        macos_release_name=Chirp-$tag-osx-x64
        
        dotnet publish ../src/Chirp.CLI/Chirp.CLI.csproj --runtime "osx-x64" -c Release -o "$macos_release_name"
        
        tar czvf "$macos_release_name.tar.gz" "$macos_release_name"

    - name: Build Linux
      shell: bash
      run: |
        tag=$(git describe --tags --abbrev=0)
        
        linux_release_name=Chirp-$tag-linux-x64
        
        echo pwd 
        
        dotnet publish ../src/Chirp.CLI/Chirp.CLI.csproj --runtime "linux-x64" -c Release -o "$linux_release_name"
        
        tar czvf "$linux_release_name.tar.gz" "$linux_release_name"
        
    - name: Build Windows
      shell: bash
      run: |
        tag=$(git describe --tags --abbrev=0)
        
        windows_release_name=Chirp-$tag-win-x64
        
        dotnet publish ../src/Chirp.CLI/Chirp.CLI.csproj --runtime "win-x64" -c Release -o "$windows_release_name"
        
        7z a -tzip "$windows_release_name.zip" "./$windows_release_name/*"
      
    - name: Publish
      uses: softprops/action-gh-release@v2
      with: 
        files: "Chirp*"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
          
